# Generated by Django 3.0.2 on 2020-01-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YelpReview',
        ),
    ]
